%%% St.Dev of the Deformation Magnitude Calculcator
% SSDM is a measure that can be used to assess within group variability in
% anatomical deformations
%
% Purpose: Calculate SSDM on a group-wise basis to assess degree of
% inter-individual anatomical variability.
%
% (1) Select y_*.nii Deformation Files generated by SPM for calculations, as
% well as a file naming string. 
%
% (2) Load files, calculate the average deformation across the three dimensions / vector fields
%
% (3) Calculate the Sum of the Square Deformations for each j_*.nii image relative to the average in 2 across
% the three dimensions (assuming 3D anatomical images produced by SPM)
%
% (4) Calculate the standard deviation from SSD in 3.
% (5) Optional masking according to selected mask image and threshold
% (6) Write Unmasked and/or Masked Average Outputs
% 
% Author: Taylor W. Uselman
%
%% Direct towards files
clear 

[fn, fp]=uigetfile('y_*.nii','Select the Deformation Files for SSDM Calculation','MultiSelect','on');
outstr = inputdlg('Enter Output File String','Prompt',1,{'_'});

no_files = size(fn,2);

%% Create Average Deformation Image
for i=1:no_files
    if i == 1
        nii = niftiread(char(strcat(fp,fn(i))));
    else
        nii_tmp = niftiread(char(strcat(fp,fn(i))));
        nii = nii + nii_tmp;
    end
end
avgnii = (nii / no_files);
niftiwrite(avgnii,char(strcat('Avg_Def_',outstr)))


%% Calculate the Sum of the Squared Error Deformation Magntitude
for i=1:no_files
    if i == 1
        nii = niftiread(char(strcat(fp,fn(i))));
        nii = (nii(:,:,:,:,1)-avgnii(:,:,:,1,1)).^2 + (nii(:,:,:,:,2)-avgnii(:,:,:,1,2)).^2 + (nii(:,:,:,:,3)-avgnii(:,:,:,1,3)).^2;
    else
        nii_tmp = niftiread(char(strcat(fp,fn(i))));
        nii_tmp = (nii_tmp(:,:,:,:,1)-avgnii(:,:,:,1,1)).^2 + (nii_tmp(:,:,:,:,2)-avgnii(:,:,:,1,2)).^2 + (nii_tmp(:,:,:,:,3)-avgnii(:,:,:,1,3)).^2;
        nii = nii + nii_tmp;
    end
end

%% Calculcate the Standard Deviation of the Deformation Magnitude (SSD)
nii = sqrt(nii / (no_files-1));
niftiwrite(nii,char(strcat('SSDM_',outstr)))

mask = questdlg('Would you like to mask the image?','Mask Image','Yes','No','Cancel','Yes');
if mask == 'Yes'
    [maskname, maskpath] = uigetfile('*.nii','Select image to use as mask','MultiSelect','off');
    fullmask = fullfile(maskpath, maskname);
    nii_mask = niftiread(fullmask);
    binthr = inputdlg('What is the value threshold for binarization?','Prompt',1,{'2000'});
    binthr = str2num(binthr{1});
    nii_mask2 = (nii_mask >= binthr);
    nii = nii .* single(nii_mask2);
    niftiwrite(nii,char(strcat('SSDM_',outstr,'_masked')))
end

fprintf('\nDone!\n\n')